# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: one
  value: initialValue 

steps:
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo $(one)
  displayName: First variable pass
- bash: echo '##vso[task.setvariable variable=one]secondValue'
  displayName: Set new variable value
- script: |
    echo ${{ variables.one }} # outputs initialValue
    echo $(one) # outputs secondValue
  displayName: Second variable pass
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-Pcomponent-tests'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
